# Generated by Django 3.0.3 on 2020-07-06 04:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description_small', models.TextField()),
                ('description_small_final', models.TextField(blank=True)),
                ('description_large', models.TextField()),
                ('description_large_final', models.TextField(blank=True)),
                ('assignor_website', models.URLField()),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('apply_until_date', models.DateTimeField(blank=True, null=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('admitted', models.BooleanField(blank=True, default=False)),
                ('contact_person_full_name', models.CharField(max_length=50, null=True)),
                ('contact_person_email', models.EmailField(max_length=254, null=True)),
                ('cover_image', models.ImageField(default='default_challenge.jpg', upload_to='challenge_pics')),
                ('prize', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('SW', 'Programming'), ('DE', 'Design'), ('HW', 'Hardware'), ('SC', 'Science'), ('MA', 'Marketing'), ('OT', 'Other')], default='OT', max_length=2)),
                ('applicants', models.ManyToManyField(blank=True, related_name='challenges', to=settings.AUTH_USER_MODEL)),
                ('assignor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_challenges', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
